---
version: "2.0"

services:
  app:
    image: forestjqg/chainimages:imgwan
    
    command:
      - "bash"
      - "-c"
    args:
      - "chmod +x /wanchain/start.sh && /wanchain/start.sh "

    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true 
      - port: 17717
        as: 17717
        to:
          - global: true
      - port: 8545
        as: 8545
        to:
          - global: true 		  
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2
        memory:
          size: 8Gi
        storage:
          size: 500Gi
          
  placement:
    akash: 
      attributes:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
